export interface Industry {
  slug: string;
  name: string;
  icon: string;
  headline: string;
  subheadline: string;
  examplePosts: { platform: 'facebook' | 'instagram' | 'tiktok'; content: string }[];
  socialProof: { name: string; business: string; quote: string };
  metaTitle: string;
  metaDescription: string;
}

export const industries: Industry[] = [
  {
    slug: 'restauracja', name: 'Restauracja', icon: '🍽️',
    headline: 'Twoja restauracja zawsze pełna — dzięki postom, które piszą się same',
    subheadline: 'Generuj apetyczne posty na FB i IG w 30 sekund. Bez agencji, bez stresu, bez pustego profilu.',
    examplePosts: [
      { platform: 'facebook', content: 'Dziś na talerzu coś, czego nie znajdziesz nigdzie indziej 🍽️ Nasz szef kuchni wstał o 5 rano, żeby to dla Was przygotować. Zarezerwuj stolik — wieczory u nas kończą się szybko. Link w bio lub zadzwoń!' },
      { platform: 'instagram', content: 'Jeden kęs i wiesz, że to było warto ✨ Smak, który zostaje w pamięci długo po ostatnim kęsie. Zapraszamy dziś od 12:00. #restauracja #polskakuchnia #jedzenie #foodie' },
      { platform: 'tiktok', content: 'Myślisz że wiesz jak smakuje [nazwa dania]? Przyjdź i daj się zaskoczyć 👨‍🍳 Rezerwacje w bio.' },
    ],
    socialProof: { name: 'Marek W.', business: 'Restauracja w Poznaniu', quote: 'PostujTo oszczędza mi 4 godziny tygodniowo. Posty wyglądają profesjonalnie, a rezerwacje wzrosły.' },
    metaTitle: 'PostujTo dla restauracji — posty na FB i IG w 30 sekund | PostujTo',
    metaDescription: 'Generuj profesjonalne posty dla swojej restauracji bez agencji. Zacznij za darmo — 5 postów gratis.',
  },
  {
    slug: 'catering', name: 'Catering / Meal prep', icon: '🥗',
    headline: 'Twój catering sam się sprzedaje — kiedy masz posty, które pokazują prawdziwą wartość',
    subheadline: 'Pokaż klientom co zyskują zamawiając od Ciebie. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Ile godzin tygodniowo tracisz na gotowanie i zakupy? 🕐 Nasi klienci odzyskują średnio 5 godzin tygodniowo — i jedzą zdrowiej niż kiedykolwiek. Sprawdź nasze menu na ten tydzień!' },
      { platform: 'instagram', content: 'Świeże, zbilansowane, dostarczone pod drzwi 🥗 Bo dobre jedzenie nie powinno być przywilejem — tylko standardem. Menu w linku w bio. #catering #zdrowejedzenie #mealprep' },
      { platform: 'tiktok', content: 'Gotowanie vs zamawianie cateringu — policzyłem co wychodzi taniej. Wynik mnie zaskoczył 👆 Sprawdź w bio.' },
    ],
    socialProof: { name: 'Anna K.', business: 'Catering dietetyczny w Krakowie', quote: 'Klienci mówią, że posty wyglądają smakowicie. Zamówienia wzrosły o 30% w miesiąc.' },
    metaTitle: 'PostujTo dla cateringu — automatyczne posty social media | PostujTo',
    metaDescription: 'Twórz posty dla swojej firmy cateringowej w 30 sekund. Pokaż klientom wartość Twojej oferty. Zacznij za darmo.',
  },
  {
    slug: 'piekarnia', name: 'Piekarnia / Cukiernia', icon: '🥐',
    headline: 'Twoja piekarnia na Instagramie — posty tak ciepłe jak chleb z pieca',
    subheadline: 'Pokaż klientom różnicę między rzemiosłem a przemysłem. Generuj posty w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Nasz piekarz wstaje o 2:00 w nocy — żebyś Ty miał świeży chleb na śniadanie 🥐 Bez konserwantów, bez ulepszaczy, za to z 30-letnim doświadczeniem. Dziś w piekarni od 6:00!' },
      { platform: 'instagram', content: 'Ten zapach... 🌾 Właśnie wyjęliśmy z pieca. Skórka chrupi, środek paruje. Przyjdź zanim rozejdzie się do południa. #piekarnia #chlebnazakwasie #rzemioslo #fresh' },
      { platform: 'tiktok', content: 'Porównaj skład chleba z marketu i nasz. 3 składniki vs 23 składniki. Różnica jest oczywista 🍞' },
    ],
    socialProof: { name: 'Zofia M.', business: 'Piekarnia rzemieślnicza w Gdańsku', quote: 'Klienci piszą, że czują zapach przez ekran. Sprzedaż w weekendy wzrosła o 40%.' },
    metaTitle: 'PostujTo dla piekarni — posty na social media w 30 sekund | PostujTo',
    metaDescription: 'Generuj ciepłe, angażujące posty dla swojej piekarni. Pokaż rzemiosło i przyciągnij stałych klientów. Zacznij za darmo.',
  },
  {
    slug: 'sklep', name: 'Sklep spożywczy', icon: '🛒',
    headline: 'Twój sklep spożywczy zawsze widoczny — nawet gdy klienci scrollują o 22:00',
    subheadline: 'Regularnie przypominaj o sobie lokalnym klientom. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🛒 Właśnie przyjechała dostawa świeżych warzyw od lokalnych rolników! Marchew, ziemniaki, buraki — wszystko dzisiaj zbierane. Zapraszamy, ilości ograniczone!' },
      { platform: 'instagram', content: 'Lokalnie, świeżo, bez kolejek w hipermarkecie 🌿 U nas znasz sprzedawcę z imienia i wiesz skąd pochodzi każdy produkt. #lokalniesklepowe #świeże #wspieramnaszych' },
      { platform: 'tiktok', content: '3 produkty z naszego sklepu, których nie znajdziesz w żadnym markecie. Sprawdź czy je znasz 👇' },
    ],
    socialProof: { name: 'Tomasz B.', business: 'Sklep osiedlowy w Łodzi', quote: 'Stali klienci mówią, że widzą nas na FB i wpadają częściej. Social media naprawdę działają.' },
    metaTitle: 'PostujTo dla sklepów spożywczych — social media bez wysiłku | PostujTo',
    metaDescription: 'Twórz posty dla swojego sklepu spożywczego w 30 sekund. Buduj lojalność lokalnych klientów. Zacznij za darmo.',
  },
  {
    slug: 'kosmetyczka', name: 'Salon kosmetyczny', icon: '💅',
    headline: 'Twój salon kosmetyczny zawsze zajęty — kiedy klientki widzą Twoje efekty w sieci',
    subheadline: 'Pokaż transformacje, buduj zaufanie, zapełniaj kalendarz. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Kiedy ostatni raz zrobiłaś coś tylko dla siebie? ✨ Nie dla rodziny, nie dla pracy — tylko dla Ciebie. Zapraszamy na chwilę oddechu i efekt, który zostanie na dłużej. Wolne terminy jeszcze w tym tygodniu!' },
      { platform: 'instagram', content: 'Przed → Po 💅 Taka metamorfoza jest możliwa w jednej wizycie. Skóra po zabiegu mówi sama za siebie. Umów się przez link w bio. #kosmetyczka #metamorfoza #pielegnacja #glow' },
      { platform: 'tiktok', content: 'Dlaczego skóra wygląda gorzej po zimie? I co zrobić żeby to zmienić w 3 tygodnie 👆' },
    ],
    socialProof: { name: 'Natalia P.', business: 'Salon kosmetyczny w Warszawie', quote: 'Klientki mówią, że znalazły mnie przez Instagram. Grafik zajęty na 3 tygodnie do przodu.' },
    metaTitle: 'PostujTo dla salonów kosmetycznych — posty które zapełniają kalendarz | PostujTo',
    metaDescription: 'Generuj posty dla swojego salonu kosmetycznego w 30 sekund. Pokaż efekty i przyciągaj nowe klientki. Zacznij za darmo.',
  },
  {
    slug: 'fryzjer', name: 'Fryzjer / Barber', icon: '✂️',
    headline: 'Twój salon fryzjerski zawsze pełny — kiedy każdy post pokazuje, że wiesz co robisz',
    subheadline: 'Przed i po, porady, terminy — wszystko gotowe w 30 sekund. Bez pisania.',
    examplePosts: [
      { platform: 'facebook', content: 'Efekt jest lepszy niż sobie wyobrażała 💇‍♀️ Przyszła z pytaniem "czy da się coś zrobić z tymi włosami?" — zobaczcie sami. Wolne terminy w tym tygodniu, pisz w wiadomości!' },
      { platform: 'instagram', content: 'Nowe cięcie, nowy vibe ✂️ Każda fryzura to nowa historia. Ta akurat opowiada o odwadze. #fryzjer #metamorfoza #nowecięcie #włosy #salon' },
      { platform: 'tiktok', content: 'Twoje włosy się puszą? Robisz jeden z tych 3 błędów pod prysznicem. Sprawdź 👇' },
    ],
    socialProof: { name: 'Magda K.', business: 'Studio Fryzjerskie w Krakowie', quote: 'Zaoszczędziłam 3 godziny tygodniowo. Posty wychodzą lepsze niż robiłam sama.' },
    metaTitle: 'PostujTo dla fryzjerów — posty na FB i IG które zapełniają grafik | PostujTo',
    metaDescription: 'Twórz posty dla swojego salonu fryzjerskiego w 30 sekund. Pokaż metamorfozy i przyciągaj nowych klientów. Zacznij za darmo.',
  },
  {
    slug: 'fitness', name: 'Fitness / Siłownia', icon: '💪',
    headline: 'Twoja siłownia lub studio fitness zawsze widoczne — posty które motywują do działania',
    subheadline: 'Pokaż transformacje, buduj społeczność, zapełniaj zajęcia. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Kasia przyszła do nas 3 miesiące temu z jednym celem. Dziś robi to, o czym wtedy nie śmiała marzyć 💪 Każdy zaczyna od pierwszego kroku. Twój może być dziś — wpadnij na trening próbny, pierwsza wizyta gratis!' },
      { platform: 'instagram', content: 'Godzina która zmienia wszystko ⚡ Energia po naszych zajęciach grupowych nie da się opisać — trzeba to poczuć. Grafik zajęć w linku w bio. #fitness #silownia #trening #motywacja' },
      { platform: 'tiktok', content: 'Co jeść po treningu żeby spalać tłuszcz a nie mięśnie? 3 zasady które zmienią Twoje wyniki 👆' },
    ],
    socialProof: { name: 'Piotr L.', business: 'Siłownia w Wrocławiu', quote: 'Liczba zapisów wzrosła o 25% po miesiącu używania PostujTo. Polecam każdemu klub fitness.' },
    metaTitle: 'PostujTo dla siłowni i fitness — posty które zapełniają zajęcia | PostujTo',
    metaDescription: 'Generuj motywujące posty dla swojego studia fitness w 30 sekund. Pokaż transformacje i buduj społeczność. Zacznij za darmo.',
  },
  {
    slug: 'stomatolog', name: 'Stomatolog', icon: '🦷',
    headline: 'Twój gabinet stomatologiczny zawsze z nowymi pacjentami — bez strachu po obu stronach',
    subheadline: 'Rozwiaj obawy, buduj zaufanie, zapełniaj kalendarz. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Wiesz że lęk przed dentystą dotyczy ponad połowy Polaków? 🦷 U nas każda wizyta jest bezbolesna — i to nie jest marketingowe hasło, to opinia naszych pacjentów. Pierwsze konsultacje w tym tygodniu jeszcze dostępne!' },
      { platform: 'instagram', content: 'Piękny uśmiech to nie luksus — to inwestycja w pewność siebie ✨ Wybielanie, aparat, licówki — sprawdź co możemy dla Ciebie zrobić. Link w bio. #stomatolog #uśmiech #zdrowiezeby' },
      { platform: 'tiktok', content: '5 pytań które ZAWSZE warto zadać dentyście, ale większość ludzi się boi zapytać 👆' },
    ],
    socialProof: { name: 'Kamila W.', business: 'Gabinet stomatologiczny w Gdyni', quote: 'Pacjenci mówią, że zaufali nam przez social media. Przyjęcia pełne na 6 tygodni.' },
    metaTitle: 'PostujTo dla stomatologów — posty które budują zaufanie pacjentów | PostujTo',
    metaDescription: 'Twórz posty dla swojego gabinetu stomatologicznego w 30 sekund. Rozwiaj obawy i przyciągaj nowych pacjentów. Zacznij za darmo.',
  },
  {
    slug: 'weterynarz', name: 'Weterynarz / Petsitter', icon: '🐾',
    headline: 'Twój gabinet weterynaryjny polecany przez właścicieli zwierząt z okolicy',
    subheadline: 'Pokaż troskę o zwierzęta, buduj zaufanie właścicieli. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Twój pies nie powie Ci, że go boli. Ale Ty możesz to zauważyć wcześniej 🐾 3 sygnały, które często ignorujemy — a które mogą być ważne. Masz pytania? Napisz do nas lub wpadnij na konsultację!' },
      { platform: 'instagram', content: 'Każdy pacjent zasługuje na najlepszą opiekę 🐕 Dziś u nas Burek i Misia — oboje wychodzą szczęśliwi. Umów wizytę przez link w bio. #weterynarz #zwierzęta #opieka #zdrowiepupila' },
      { platform: 'tiktok', content: 'Wyjeżdżasz i nie wiesz co zrobić z pupilem? Pokaż jak wygląda opieka u nas 🐶' },
    ],
    socialProof: { name: 'Joanna S.', business: 'Lecznica weterynaryjna w Katowicach', quote: 'Nowi klienci mówią, że znaleźli nas na Instagramie. PostujTo oszczędza mi mnóstwo czasu.' },
    metaTitle: 'PostujTo dla weterynarzy — posty które budują zaufanie właścicieli zwierząt | PostujTo',
    metaDescription: 'Generuj posty dla swojego gabinetu weterynaryjnego w 30 sekund. Pokaż troskę i przyciągaj nowych klientów. Zacznij za darmo.',
  },
  {
    slug: 'handel', name: 'Handel / Sklep', icon: '🏪',
    headline: 'Twój sklep sprzedaje więcej — kiedy klienci widzą go w social mediach każdego dnia',
    subheadline: 'Nowe kolekcje, inspiracje stylizacyjne, bestsellery — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Właśnie dostaliśmy nową kolekcję i już wiemy, że zostanie z nami krótko 🛍️ Pierwsze zdjęcia w galerii — jeśli coś złapie Twoje oko, pisz w wiadomości. Rezerwujemy bez przedpłaty!' },
      { platform: 'instagram', content: 'Ten kolor tej wiosny jest wszędzie ✨ A my mamy go w 3 fasonach. Sprawdź który pasuje do Twojego stylu — link w bio. #moda #nowakolekcja #styl #ootd' },
      { platform: 'tiktok', content: 'Nie wiesz co założyć na [okazja]? 3 gotowe stylizacje z naszego sklepu — każda do 200 zł 👗' },
    ],
    socialProof: { name: 'Beata R.', business: 'Sklep odzieżowy w Poznaniu', quote: 'Klientki przychodzą i mówią, że widziały post na Instagramie. Sprzedaż online wzrosła.' },
    metaTitle: 'PostujTo dla sklepów — posty które zwiększają sprzedaż | PostujTo',
    metaDescription: 'Twórz posty dla swojego sklepu w 30 sekund. Pokazuj nowości, buduj społeczność i sprzedawaj więcej. Zacznij za darmo.',
  },
  {
    slug: 'rekodzielnictwo', name: 'Rękodzielnictwo', icon: '🧶',
    headline: 'Twoje rękodzieło doceniane przez klientów z całej Polski — dzięki social mediom',
    subheadline: 'Pokaż proces tworzenia, unikalność i pasję. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Każdy produkt wychodzi z moich rąk — nie z taśmy produkcyjnej 🧶 Ten sweter powstawał 3 tygodnie. Efekt? Jego właścicielka napisała że "nigdy w życiu nie miała czegoś tak ciepłego i wyjątkowego". To jest po prostu moja praca!' },
      { platform: 'instagram', content: 'Za kulisami ✨ Tak powstaje każdy produkt który wysyłam. Godziny pracy, mnóstwo uwagi, zero masowej produkcji. Efekty w galerii — zamówienia przez DM. #rekodzielnictwo #handmade #rękodzieło' },
      { platform: 'tiktok', content: 'Od surowego materiału do gotowego produktu — cały proces w 60 sekund 🧵 Warto wiedzieć co kupujesz.' },
    ],
    socialProof: { name: 'Ela K.', business: 'Pracownia rękodzieła w Krakowie', quote: 'Instagram stał się moim głównym kanałem sprzedaży. PostujTo pomaga mi publikować regularnie.' },
    metaTitle: 'PostujTo dla twórców rękodzieła — social media które sprzedają | PostujTo',
    metaDescription: 'Generuj posty dla swojego rękodzieła w 30 sekund. Pokaż proces tworzenia i przyciągaj klientów z całej Polski. Zacznij za darmo.',
  },
  {
    slug: 'budowlanka', name: 'Budowlanka / Remont', icon: '🏗️',
    headline: 'Twoja firma budowlana z pełnym grafikiem — kiedy klienci widzą jak pracujesz',
    subheadline: 'Pokaż realizacje, buduj zaufanie, eliminuj obiekcje. Posty gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Remont łazienki: od projektu do odbioru w 3 tygodnie ✅ Klient nie musiał nic pilnować — daliśmy mu klucze do gotowego. Tak wygląda nasza praca. Terminy na kwiecień jeszcze dostępne — pisz!' },
      { platform: 'instagram', content: 'Przed → Po 🏗️ Ta kuchnia to teraz ulubione miejsce w domu klienta. Efekt po 2 tygodniach pracy. Twój remont może wyglądać tak samo — link w bio. #remont #budownictwo #metamorfoza #wnętrza' },
      { platform: 'tiktok', content: '3 rzeczy które ZAWSZE sprawdzaj zanim podpiszesz umowę z ekipą remontową. Zaoszczędzi Ci to nerwów i pieniędzy 👆' },
    ],
    socialProof: { name: 'Krzysztof J.', business: 'Firma remontowa w Warszawie', quote: 'Klienci dzwonią i mówią, że znaleźli nas na Facebooku. Zapełniłem kalendarz na 3 miesiące.' },
    metaTitle: 'PostujTo dla firm budowlanych — posty które zapełniają grafik | PostujTo',
    metaDescription: 'Twórz posty dla swojej firmy budowlanej w 30 sekund. Pokaż realizacje i przyciągaj klientów z okolicy. Zacznij za darmo.',
  },
  {
    slug: 'uslugi', name: 'Usługi / Rzemiosło', icon: '🔧',
    headline: 'Twoja firma usługowa polecana w okolicy — kiedy klienci widzą Cię regularnie w sieci',
    subheadline: 'Realizacje, opinie, porady — wszystko gotowe w 30 sekund. Bez pisania.',
    examplePosts: [
      { platform: 'facebook', content: 'Problem zgłoszony o 8:00, rozwiązany do południa ✅ Tak wygląda nasza praca na co dzień. Nie ma rzeczy, której nie można naprawić — pod warunkiem że trafi w dobre ręce. Wolne terminy w tym tygodniu!' },
      { platform: 'instagram', content: 'Solidna robota mówi sama za siebie 🔧 Każde zlecenie traktujemy jak własny dom. Efekty w galerii — kontakt przez link w bio. #usługi #fachowiec #solidnarobota #rzemiosło' },
      { platform: 'tiktok', content: 'Jak wybrać dobrego fachowca? 5 pytań które musisz zadać zanim kogoś zatrudnisz 👆' },
    ],
    socialProof: { name: 'Artur M.', business: 'Firma usługowa w Łodzi', quote: 'Przez social media pozyskuję 2-3 nowych klientów miesięcznie. PostujTo robi to za mnie.' },
    metaTitle: 'PostujTo dla firm usługowych — social media które budują zaufanie | PostujTo',
    metaDescription: 'Generuj posty dla swojej firmy usługowej w 30 sekund. Pokaż realizacje i przyciągaj klientów z okolicy. Zacznij za darmo.',
  },
  {
    slug: 'fotograf', name: 'Fotograf', icon: '📸',
    headline: 'Twoja fotografia widoczna tam gdzie są Twoi klienci — bez godzin spędzonych na pisaniu',
    subheadline: 'Portfolio, kulisy sesji, porady — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Chwila, która zostanie na zawsze 📸 Ta para powiedziała że "bali się sesji, bo nie lubią zdjęć". Efekt mówi sam za siebie — zobaczcie. Terminy na sesje letnie wypełniają się szybko, pisz jeśli chcesz zarezerwować datę!' },
      { platform: 'instagram', content: 'Każde zdjęcie to decyzja podjęta w ułamku sekundy ✨ I właśnie to kocham w tej pracy. Nowe portfolio w galerii — link w bio. #fotograf #sesja #fotografia #portret' },
      { platform: 'tiktok', content: 'Nie lubisz być fotografowany? Zdradzę Ci co robię żebyś zapomniał o aparacie 📷' },
    ],
    socialProof: { name: 'Michał T.', business: 'Studio fotograficzne w Wrocławiu', quote: 'Instagram generuje połowę moich zapytań. PostujTo sprawia, że zawsze jestem aktywny.' },
    metaTitle: 'PostujTo dla fotografów — social media które przyciągają klientów | PostujTo',
    metaDescription: 'Twórz posty dla swojej działalności fotograficznej w 30 sekund. Pokaż portfolio i przyciągaj nowych klientów. Zacznij za darmo.',
  },
  {
    slug: 'ogrodnik', name: 'Ogrodnik / Landscaping', icon: '🌿',
    headline: 'Twoja firma ogrodnicza z pełnym kalendarzem — kiedy klienci widzą Twoje realizacje',
    subheadline: 'Przed i po, porady sezonowe, wolne terminy — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Ten ogród wyglądał jak zarośnięty plac budowy. Teraz właściciel pije tam kawę co rano 🌿 Efekt po jednym dniu pracy naszej ekipy. Terminy wiosenne szybko się zapełniają — pisz jeśli chcesz zdążyć przed sezonem!' },
      { platform: 'instagram', content: 'Przed → Po 🌱 Tak wygląda nasz standardowy dzień pracy. Jeden ogród, jeden dzień, kompletna zmiana. Twój może być następny — link w bio. #ogrodnik #ogrod #landscaping #zielen' },
      { platform: 'tiktok', content: 'Co zrobić w ogrodzie jako pierwsze po zimie? 5 zadań które musisz wykonać w marcu 🌿' },
    ],
    socialProof: { name: 'Paweł G.', business: 'Firma ogrodnicza w Poznaniu', quote: 'Sezon jeszcze nie zaczął, a już mam pełen grafik. Social media naprawdę działają.' },
    metaTitle: 'PostujTo dla ogrodników — posty które zapełniają kalendarz na cały sezon | PostujTo',
    metaDescription: 'Generuj posty dla swojej firmy ogrodniczej w 30 sekund. Pokaż realizacje i zapełniaj terminarz na cały sezon. Zacznij za darmo.',
  },
  {
    slug: 'transport', name: 'Transport / Spedycja', icon: '🚛',
    headline: 'Twoja firma transportowa jako pierwsza na myśli klienta — dzięki regularnej obecności w sieci',
    subheadline: 'Realizacje, terminowość, zaufanie — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Trasa Warszawa–Berlin, 580 km, dostawa na czas ✅ Klient czekał na towar od tygodnia — my dowieźliśmy w 24h. Bo terminowość to nie bonus — to nasz standard. Zapytaj o wycenę!' },
      { platform: 'instagram', content: 'Każda przesyłka to nasze zobowiązanie 🚛 GPS, ubezpieczenie, kontakt przez całą trasę. Twój towar jest bezpieczny. Kontakt przez link w bio. #transport #spedycja #logistyka #transport' },
      { platform: 'tiktok', content: 'Co się dzieje z Twoim towarem podczas transportu? Pokazuję jak to wygląda od środka 🚛' },
    ],
    socialProof: { name: 'Dariusz K.', business: 'Firma transportowa w Katowicach', quote: 'Klienci mówią, że wyglądamy profesjonalnie w sieci. PostujTo pomaga mi budować markę.' },
    metaTitle: 'PostujTo dla firm transportowych — social media które budują zaufanie klientów | PostujTo',
    metaDescription: 'Twórz posty dla swojej firmy transportowej w 30 sekund. Pokaż terminowość i profesjonalizm. Zacznij za darmo.',
  },
  {
    slug: 'prawnik', name: 'Kancelaria / Prawnik', icon: '⚖️',
    headline: 'Twoja kancelaria widoczna gdy klient szuka pomocy — nie po tym jak się zagubi',
    subheadline: 'Edukacja prawna, case studies, porady — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Podpisałeś umowę, której nie przeczytałeś do końca? ⚖️ To zdarza się częściej niż myślisz — i często ma poważne konsekwencje. Przeczytaj nasz post o 3 klauzulach, na które zawsze warto zwrócić uwagę. Pytania? Napisz do nas!' },
      { platform: 'instagram', content: 'Prawo nie musi być skomplikowane — jeśli ktoś Ci je dobrze wyjaśni 📋 Kolejny case study w galerii. Obserwuj jeśli chcesz wiedzieć jak chronić swoje prawa. #prawo #prawnik #kancelaria #prawaobywatela' },
      { platform: 'tiktok', content: 'Wynajmujesz mieszkanie? Sprawdź czy Twoja umowa nie ma tych 3 niebezpiecznych zapisów ⚖️' },
    ],
    socialProof: { name: 'Marta Z.', business: 'Kancelaria prawna w Warszawie', quote: 'Klienci mówią, że posty brzmią autorytatywnie. PostujTo pomaga mi dotrzeć do nowych osób.' },
    metaTitle: 'PostujTo dla kancelarii i prawników — social media które budują autorytet | PostujTo',
    metaDescription: 'Generuj posty edukacyjne dla swojej kancelarii w 30 sekund. Buduj autorytet i przyciągaj klientów. Zacznij za darmo.',
  },
  {
    slug: 'korepetycje', name: 'Korepetycje', icon: '📚',
    headline: 'Twoje korepetycje polecane przez rodziców z okolicy — kiedy wyniki mówią same za siebie',
    subheadline: 'Wyniki uczniów, porady dla rodziców, wolne miejsca — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Kacper przyszedł do mnie z dwójką z matematyki. Po 2 miesiącach dostał czwórkę na semestr 📚 Mama powiedziała że "w końcu nie boi się sprawdzianów". Właśnie po to to robię. Wolne miejsca jeszcze w tym miesiącu!' },
      { platform: 'instagram', content: 'Matematyka nie musi być stresem — musi być zrozumiana ✏️ Każde zadanie ma logikę, trzeba ją tylko pokazać. Sprawdź opinie rodziców w linku w bio. #korepetycje #matematyka #edukacja #nauka' },
      { platform: 'tiktok', content: 'Twoje dziecko twierdzi że matematyka jest za trudna? Prawdopodobnie chodzi o jeden konkretny problem. Tłumaczę 👆' },
    ],
    socialProof: { name: 'Monika L.', business: 'Korepetycje online z Trójmiasta', quote: 'Grafik pełny na 2 miesiące do przodu. Rodzice piszą, że znaleźli mnie przez Facebooka.' },
    metaTitle: 'PostujTo dla korepetytorów — posty które przyciągają uczniów i rodziców | PostujTo',
    metaDescription: 'Twórz posty dla swoich korepetycji w 30 sekund. Pokaż wyniki uczniów i zapełniaj kalendarz. Zacznij za darmo.',
  },
  {
    slug: 'edukacja', name: 'Edukacja / Kursy', icon: '🎓',
    headline: 'Twoje kursy i szkolenia wybierane przez osoby, które serio chcą się rozwijać',
    subheadline: 'Wyniki absolwentów, zajawki treści, zapisy — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Ania po naszym kursie dostała podwyżkę o 40% 🎓 Powiedziała że "w końcu rozumie jak działa rynek i jak na nim zarabiać". To jest właśnie cel naszego szkolenia. Kolejna edycja startuje za 2 tygodnie — zostało 5 miejsc!' },
      { platform: 'instagram', content: 'Wiedza to jedyna inwestycja której nikt Ci nie może zabrać 📖 Nowy moduł już dostępny dla uczestników. Zapisz się przez link w bio. #kursy #edukacja #rozwoj #szkolenia' },
      { platform: 'tiktok', content: 'Nauczył się tej jednej umiejętności i zarobił o 3000 zł więcej w następnym miesiącu. Oto co konkretnie zrobił 👆' },
    ],
    socialProof: { name: 'Rafał N.', business: 'Platforma kursów online', quote: 'Liczba zapisów wzrosła o 40% po regularnym postowaniu. PostujTo to najlepsza inwestycja.' },
    metaTitle: 'PostujTo dla szkoleń i kursów — posty które zapełniają listy zapisów | PostujTo',
    metaDescription: 'Generuj posty dla swoich kursów i szkoleń w 30 sekund. Pokaż wyniki absolwentów i zapełniaj listy zapisów. Zacznij za darmo.',
  },
  {
    slug: 'nieruchomosci', name: 'Nieruchomości', icon: '🏠',
    headline: 'Twoje oferty nieruchomości sprzedają się szybciej — kiedy klienci widzą Cię regularnie',
    subheadline: 'Oferty tygodnia, porady dla kupujących, realizacje — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Sprzedane w 11 dni 🏠 Mieszkanie 3-pokojowe, które stało na rynku od 4 miesięcy u poprzedniego agenta. Co zrobiliśmy inaczej? Home staging, profesjonalne zdjęcia i właściwa cena od pierwszego dnia. Chcesz sprzedać szybko i dobrze — napisz!' },
      { platform: 'instagram', content: 'Okno z tym widokiem i kawa o 7:00 rano ☀️ Nowa oferta właśnie w naszym portfolio. Szczegóły w linku w bio. #nieruchomości #mieszkanie #sprzedazMieszkania #dom' },
      { platform: 'tiktok', content: 'Kupujesz pierwsze mieszkanie? 5 rzeczy które sprawdź ZANIM podpiszesz umowę deweloperską 🏠' },
    ],
    socialProof: { name: 'Agnieszka W.', business: 'Biuro nieruchomości w Warszawie', quote: 'Klienci mówią, że oferta wygląda profesjonalnie. PostujTo pomaga mi wyróżnić się na rynku.' },
    metaTitle: 'PostujTo dla agentów nieruchomości — social media które sprzedają | PostujTo',
    metaDescription: 'Twórz posty dla swojego biura nieruchomości w 30 sekund. Pokazuj oferty i buduj markę eksperta. Zacznij za darmo.',
  },
  {
    slug: 'turystyka', name: 'Turystyka / Hotel', icon: '✈️',
    headline: 'Twój hotel lub biuro podróży zawsze z zarezerwowanymi terminami — dzięki postom które wywołują tęsknotę',
    subheadline: 'Zdjęcia, last minute, atrakcje — wszystko gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: 'Obudzić się z tym widokiem... ☀️ Gościom zostało już tylko 2 wolne terminy na lipiec. Jeśli planujesz urlop — nie zwlekaj. Link do rezerwacji w komentarzu!' },
      { platform: 'instagram', content: 'Twój telefon odkłada się sam ✨ Tu liczy się tylko śniadanie, widok i rozmowa z bliskimi. Czy tego właśnie potrzebujesz? Link w bio. #hotel #wakacje #urlop #wypoczynek #polska' },
      { platform: 'tiktok', content: '3 miejsca w Polsce które wyglądają jak z Włoch — i są 3x tańsze. Sprawdź czy je znasz 🏖️' },
    ],
    socialProof: { name: 'Wojciech H.', business: 'Hotel górski w Zakopanem', quote: 'Rezerwacje przez social media wzrosły o 35%. PostujTo pomaga nam być widocznymi przez cały rok.' },
    metaTitle: 'PostujTo dla hoteli i biur podróży — posty które zapełniają rezerwacje | PostujTo',
    metaDescription: 'Generuj posty dla swojego hotelu lub biura podróży w 30 sekund. Pokaż klimat i zapełniaj kalendarze. Zacznij za darmo.',
  },
];

// 105 tematów (5 per branża) — używane na Landing Pages i w tabeli Supabase industry_inspirations
// Typ: 'pain' = Ból klienta, 'result' = Rezultat, 'relation' = Kulisy/Relacja
export const INDUSTRY_TOPICS: Record<string, { title: string; type: 'pain' | 'result' | 'relation' }[]> = {
  restauracja: [
    { title: 'Dlaczego nasza [Danie Dnia] smakuje inaczej niż wszędzie?', type: 'relation' },
    { title: '3 powody, by dziś nie gotować obiadu w domu.', type: 'pain' },
    { title: 'Zajrzyj do naszej kuchni: Jak powstaje Twój ulubiony sos?', type: 'relation' },
    { title: 'Romantyczna kolacja czy szybki lunch? Mamy stolik dla Ciebie.', type: 'result' },
    { title: 'Co nasi goście mówią o [Danie]? Zobacz opinie!', type: 'result' },
  ],
  catering: [
    { title: 'Ile czasu marnujesz na zakupy i gotowanie w tygodniu?', type: 'pain' },
    { title: 'Jak schudnąć 3 kg w miesiąc bez głodówki? Nasz plan.', type: 'result' },
    { title: 'Co znajdziesz w jutrzejszej torbie? Menu na jutro!', type: 'relation' },
    { title: '3 mity o cateringu dietetycznym, które musisz znać.', type: 'pain' },
    { title: 'Z czego gotujemy? Poznaj naszych lokalnych dostawców.', type: 'relation' },
  ],
  piekarnia: [
    { title: 'Dlaczego nasz chleb na zakwasie nie czerstwieje po jednym dniu?', type: 'pain' },
    { title: 'Zapach, który budzi całą ulicę — co właśnie wyjęliśmy z pieca!', type: 'result' },
    { title: 'Chleb z marketu vs rzemieślniczy: zobacz różnicę w składzie.', type: 'pain' },
    { title: 'Twoje idealne śniadanie zaczyna się tutaj. Co wybierasz?', type: 'result' },
    { title: 'Nasz piekarz pracuje, gdy Ty śpisz — kulisy nocy w piekarni.', type: 'relation' },
  ],
  sklep: [
    { title: 'Nowa dostawa świeżych warzyw! Zobacz, co dziś przyjechało.', type: 'result' },
    { title: '3 produkty z naszego sklepu, które musisz mieć w kuchni.', type: 'result' },
    { title: 'Lokalne produkty, których nie znajdziesz w wielkich marketach.', type: 'pain' },
    { title: 'Szybki przepis na kolację z produktów z naszej półki.', type: 'result' },
    { title: 'Jesteśmy tu dla Was — poznaj naszą ekipę sprzedawców!', type: 'relation' },
  ],
  kosmetyczka: [
    { title: 'Twoja skóra po zimie potrzebuje ratunku. Zobacz nasz plan.', type: 'pain' },
    { title: 'Metamorfoza paznokci: Od zniszczonych do perfekcyjnych.', type: 'result' },
    { title: '5 minut dla siebie — dlaczego każda kobieta potrzebuje wizyty u nas?', type: 'result' },
    { title: 'Czym pracujemy? Zobacz nasze profesjonalne kosmetyki.', type: 'relation' },
    { title: 'Najczęściej zadawane pytania o zabieg [Nazwa]. Odpowiadamy!', type: 'pain' },
  ],
  fryzjer: [
    { title: 'Twoje włosy się puszą? Przestań robić te 3 błędy pod prysznicem.', type: 'pain' },
    { title: 'Metamorfoza miesiąca: od spalonego blondu do lśniącego brązu.', type: 'result' },
    { title: 'Nasze nowe narzędzia — dlaczego inwestujemy w najlepszy sprzęt?', type: 'relation' },
    { title: 'Barberski klasyk czy nowoczesny fade? Co wybierasz?', type: 'relation' },
    { title: 'Szybkie odświeżenie wyglądu przed weekendem — mamy wolne terminy!', type: 'result' },
  ],
  fitness: [
    { title: 'Boisz się pierwszej wizyty na siłowni? Nie u nas! Zobacz dlaczego.', type: 'pain' },
    { title: 'Trening personalny vs samodzielny: Co daje szybsze efekty?', type: 'pain' },
    { title: 'Twoja godzina mocy — energia z naszych zajęć grupowych!', type: 'result' },
    { title: 'Co jeść po treningu, by spalać tłuszcz? Podpowiadamy.', type: 'result' },
    { title: 'Nasi klubowicze zmieniają życie — poznaj historię [Imię].', type: 'relation' },
  ],
  stomatolog: [
    { title: 'Boisz się dentysty? U nas każda wizyta jest bezbolesna.', type: 'pain' },
    { title: 'Wybielanie zębów: Efekty już po pierwszej wizycie. Przed i po.', type: 'result' },
    { title: '5 pytań, które warto zadać dentyście, a zwykle nie zadajemy.', type: 'pain' },
    { title: 'Jak dbać o zęby między wizytami? 3 rady od naszego ortodonty.', type: 'result' },
    { title: 'Poznaj nasz gabinet — komfort, który poczujesz już w poczekalni.', type: 'relation' },
  ],
  weterynarz: [
    { title: 'Twój pupil nie powie Ci, że go boli. Na co zwrócić uwagę?', type: 'pain' },
    { title: 'Pierwsza wizyta u weterynarza — jak oszczędzić stresu zwierzakowi?', type: 'result' },
    { title: 'Szczęśliwy pies to zdrowy pies. Zadbaj o profilaktykę.', type: 'result' },
    { title: 'Wyjeżdżasz? Zostaw pupila w dobrych rękach — jak u nas mieszkają.', type: 'relation' },
    { title: 'Nasi pacjenci to nasza pasja — zobacz dzisiejszych gości!', type: 'relation' },
  ],
  handel: [
    { title: 'Nie wiesz, co założyć na [Okazja]? Mamy 3 gotowe stylizacje.', type: 'pain' },
    { title: 'Nowa kolekcja już w sklepie! Zobacz nasze ulubione modele.', type: 'result' },
    { title: 'Jakość, którą poczujesz — zobacz zbliżenie na materiał.', type: 'result' },
    { title: 'Wasze zdjęcia w naszych ubraniach — dziękujemy za zaufanie!', type: 'relation' },
    { title: 'Bestseller tygodnia: Dlaczego wszyscy kupują [Produkt]?', type: 'result' },
  ],
  rekodzielnictwo: [
    { title: 'Dlaczego rękodzieło to idealny prezent? Unikalność ma znaczenie.', type: 'result' },
    { title: 'Z warsztatu: Zobacz, jak powstaje [Produkt] od pierwszej nitki.', type: 'relation' },
    { title: 'Personalizacja: Napiszemy na produkcie, co tylko zechcesz!', type: 'result' },
    { title: 'Detale, które robią różnicę — zbliżenie na wykonanie.', type: 'result' },
    { title: 'Pakowanie prezentowe w cenie! Zobacz, jak pięknie wysyłamy paczki.', type: 'relation' },
  ],
  budowlanka: [
    { title: 'Zły remont to koszmar. Zobacz, jak pracujemy z dbałością o detale.', type: 'pain' },
    { title: 'Od surowych ścian do wymarzonego salonu — nasza ostatnia realizacja.', type: 'result' },
    { title: '3 rzeczy, o których zapominasz przy planowaniu instalacji elektrycznej.', type: 'pain' },
    { title: 'Czystość na budowie? Tak, u nas to standard.', type: 'relation' },
    { title: 'Terminy na sezon — zarezerwuj swoją ekipę już teraz!', type: 'result' },
  ],
  uslugi: [
    { title: 'Jak wybrać rzetelnego fachowca? 5 pytań, które musisz zadać.', type: 'pain' },
    { title: 'Nasza realizacja tygodnia — z problemem do rozwiązania w jeden dzień.', type: 'result' },
    { title: 'Transparentna wycena: Skąd pochodzi cena naszej usługi?', type: 'relation' },
    { title: 'Gwarancja na każdą usługę — co to oznacza w praktyce?', type: 'result' },
    { title: 'Poznaj nasz zespół — ludzie, którym możesz zaufać swoje sprawy.', type: 'relation' },
  ],
  fotograf: [
    { title: 'Nie lubisz być na zdjęciach? Sprawię, że poczujesz się swobodnie.', type: 'pain' },
    { title: 'Sesja rodzinna: Idealna pamiątka, która nie wyblaknie.', type: 'result' },
    { title: 'Jak przygotować się do sesji biznesowej? 5 szybkich rad.', type: 'result' },
    { title: 'Zza kulis: Jak wygląda sesja w plenerze od strony fotografa.', type: 'relation' },
    { title: 'Ostatnie wolne terminy na sesje komunijne/ślubne!', type: 'result' },
  ],
  ogrodnik: [
    { title: 'Wiosna w ogrodzie — co zrobić w pierwszej kolejności?', type: 'pain' },
    { title: 'Przed i po: Jak w 3 godziny zmieniliśmy ten ogród nie do poznania.', type: 'result' },
    { title: 'Top 5 roślin, które wyglądają pięknie i nie wymagają uwagi.', type: 'result' },
    { title: 'Jeden dzień z naszą ekipą — jak wygląda kompleksowa pielęgnacja?', type: 'relation' },
    { title: 'Zamów przegląd ogródka przed sezonem — wolne terminy!', type: 'result' },
  ],
  transport: [
    { title: 'Co się dzieje z Twoim towarem na granicy? Jak uniknąć przestojów.', type: 'pain' },
    { title: 'Trasa PL-DE w 24h. Kolejny ładunek bezpiecznie u klienta.', type: 'result' },
    { title: 'Poznajcie Darka — naszego mistrza kierownicy z 10-letnim stażem.', type: 'relation' },
    { title: 'Jak pakujemy kruche towary, by dojeżdżały w 100% nieuszkodzone?', type: 'result' },
    { title: 'Nasz GPS śledzi każdą przesyłkę w czasie rzeczywistym.', type: 'relation' },
  ],
  prawnik: [
    { title: '3 błędy przy podpisywaniu umowy najmu, które mogą Cię drogo kosztować.', type: 'pain' },
    { title: 'Jak skutecznie dochodzić swoich praw bez znajomości prawa?', type: 'pain' },
    { title: 'Wygraliśmy sprawę o odszkodowanie dla poszkodowanego w wypadku.', type: 'result' },
    { title: 'Bezpłatna konsultacja: Co Ci przysługuje przed podjęciem decyzji o pozwie?', type: 'result' },
    { title: 'Poznaj nasz zespół — prawnicy, którym możesz zaufać swoje sprawy.', type: 'relation' },
  ],
  korepetycje: [
    { title: 'Matematyka nie musi być trudna. Pokażemy Ci sposób na [Temat].', type: 'result' },
    { title: 'Twoje dziecko stresuje się szkołą? Pomóż mu odzyskać pewność siebie.', type: 'pain' },
    { title: 'Wyniki naszych uczniów: Średnia ocen skoczyła o 1.5 stopnia!', type: 'result' },
    { title: 'Zajęcia online vs stacjonarne — co wybrać dla Twojego dziecka?', type: 'pain' },
    { title: 'Ostatnie miejsca w grupach przygotowujących do matury!', type: 'result' },
  ],
  edukacja: [
    { title: 'Naucz się [Umiejętność] w 30 dni i zacznij zarabiać więcej.', type: 'result' },
    { title: 'Dlaczego stare metody nauki nie działają? Poznaj nasz system.', type: 'pain' },
    { title: 'Zajrzyj do platformy: Jak wyglądają nasze lekcje wideo.', type: 'relation' },
    { title: 'Certyfikat, który otwiera drzwi — gdzie pracują nasi absolwenci?', type: 'result' },
    { title: 'Inwestycja w siebie to jedyna lokata, która się nie dewaluuje.', type: 'result' },
  ],
  nieruchomosci: [
    { title: 'Jak kupić pierwsze mieszkanie i nie oszaleć od formalności?', type: 'pain' },
    { title: 'Oferta tygodnia: Mieszkanie z tarasem, w którym się zakochasz.', type: 'result' },
    { title: 'Flip czy najem? W co teraz najlepiej zainwestować kapitał?', type: 'pain' },
    { title: 'Pustostany nie zarabiają. Zobacz, jak szybko znajdujemy najemców.', type: 'result' },
    { title: 'Dzień agenta: ile km zrobiliśmy, by znaleźć dom marzeń.', type: 'relation' },
  ],
  turystyka: [
    { title: 'Zapomnij o mailach i telefonach. Twój reset zaczyna się tutaj.', type: 'pain' },
    { title: 'Co zwiedzić w okolicy? 3 ukryte miejsca z dala od tłumów.', type: 'result' },
    { title: 'Śniadanie z widokiem na [Góry/Morze] — tak może wyglądać Twój poranek.', type: 'result' },
    { title: 'Poznaj ekipę, która zadba o Twój wypoczynek.', type: 'relation' },
    { title: 'Last minute: Wolny pokój na weekend w specjalnej cenie!', type: 'result' },
  ],
};
