export interface Industry {
  slug: string;
  name: string;
  icon: string;
  headline: string;
  subheadline: string;
  examplePosts: { platform: 'facebook' | 'instagram' | 'tiktok'; content: string }[];
  socialProof: { name: string; business: string; quote: string };
  metaTitle: string;
  metaDescription: string;
}

export const industries: Industry[] = [
  {
    slug: 'restauracja', name: 'Restauracja', icon: '🍽️',
    headline: 'Twoja restauracja zawsze pełna gości — dzięki social mediom',
    subheadline: 'Generuj apetyczne posty na FB i IG w 30 sekund. Bez agencji, bez stresu.',
    examplePosts: [
      { platform: 'facebook', content: '🍽️ Dziś polecamy nasz hit tygodnia — [Danie]. Świeże składniki, domowy smak. Zarezerwuj stolik już teraz! 👇' },
      { platform: 'instagram', content: 'Smak, który zostaje w pamięci 🌟 Sprawdź nasze menu i zarezerwuj miejsce. #restauracja #jedzenie #pyszne' },
      { platform: 'tiktok', content: 'Zajrzyj do naszej kuchni 👨‍🍳 Jak powstaje Twój ulubiony sos? #restauracja #food #kuchnia' },
    ],
    socialProof: { name: 'Marek W.', business: 'Restauracja w Poznaniu', quote: 'PostujTo oszczędza mi 4 godziny tygodniowo. Posty wyglądają profesjonalnie, a rezerwacje wzrosły.' },
    metaTitle: 'PostujTo dla restauracji — automatyczne posty social media | PostujTo',
    metaDescription: 'Generuj profesjonalne posty dla restauracji na FB i IG w 30 sekund. Zacznij za darmo.',
  },
  {
    slug: 'catering', name: 'Catering / Meal prep', icon: '🥗',
    headline: 'Twój catering sprzedaje się sam — dzięki social mediom',
    subheadline: 'Posty, które pokazują świeżość i smak. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🥗 Nowe menu na ten tydzień! Świeże, zbilansowane, dostarczone pod drzwi. Zamów do środy 👇' },
      { platform: 'instagram', content: 'Zdrowe jedzenie bez wysiłku ✅ Twój tygodniowy catering czeka. #mealprep #dieta #zdrowie' },
      { platform: 'tiktok', content: 'Jak wyglądają nasze torby na dziś? Zajrzyj! #catering #mealprep #zdrowejedzenie' },
    ],
    socialProof: { name: 'Anna K.', business: 'Catering dietetyczny w Krakowie', quote: 'Klienci mówią, że posty wyglądają smakowicie. Zamówienia wzrosły o 30% w miesiąc.' },
    metaTitle: 'PostujTo dla cateringu — posty social media w 30 sekund | PostujTo',
    metaDescription: 'Automatyczne posty dla firmy cateringowej. Pokaż świeżość i smak na FB i IG.',
  },
  {
    slug: 'piekarnia', name: 'Piekarnia / Cukiernia', icon: '🥐',
    headline: 'Twoja piekarnia pachnie sukcesem — w social mediach też',
    subheadline: 'Posty z ciepłym klimatem rzemiosła. Gotowe zanim wystygnie pieczywo.',
    examplePosts: [
      { platform: 'facebook', content: '🥐 Właśnie wyjęliśmy z pieca! Świeży chleb na zakwasie czeka. Zapraszamy od [GODZINA] 🌅' },
      { platform: 'instagram', content: 'Zapach świeżego chleba przez ekran 😍 Wpadnij do nas dziś rano. #piekarnia #chleb #rzemiosło' },
      { platform: 'tiktok', content: 'Nasz piekarz pracuje, gdy Ty śpisz — kulisy nocy w piekarni 🌙 #piekarnia #bread #rzemioslo' },
    ],
    socialProof: { name: 'Zofia M.', business: 'Piekarnia rzemieślnicza w Gdańsku', quote: 'Klienci piszą, że czują zapach przez ekran. Sprzedaż w weekendy wzrosła o 40%.' },
    metaTitle: 'PostujTo dla piekarni — posty social media w 30 sekund | PostujTo',
    metaDescription: 'Generuj ciepłe, rzemieślnicze posty dla piekarni i cukierni. Zacznij za darmo.',
  },
  {
    slug: 'sklep', name: 'Sklep spożywczy', icon: '🛒',
    headline: 'Twój sklep spożywczy — aktywny w social mediach bez wysiłku',
    subheadline: 'Pokaż świeżość produktów i lokalność. Post gotowy w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🥦 Dziś przyjechały świeże warzywa od lokalnych rolników! Zapraszamy — do wyczerpania zapasów 🛒' },
      { platform: 'instagram', content: 'Lokalnie i świeżo 💚 Nasze półki właśnie uzupełnione. Wpadnij do nas! #sklep #lokalnie #świeże' },
      { platform: 'tiktok', content: '3 produkty z naszego sklepu, które musisz mieć w kuchni 🍳 #sklep #food #kuchnia' },
    ],
    socialProof: { name: 'Tomasz B.', business: 'Sklep osiedlowy w Łodzi', quote: 'Stali klienci mówią, że widzą nas na FB i wpadają częściej. Social media naprawdę działają.' },
    metaTitle: 'PostujTo dla sklepów — automatyczne posty social media | PostujTo',
    metaDescription: 'Posty dla sklepu spożywczego na FB i IG w 30 sekund. Pokaż świeżość i lokalność.',
  },
  {
    slug: 'kosmetyczka', name: 'Salon kosmetyczny', icon: '💅',
    headline: 'Twój salon kosmetyczny — pełen rezerwacji przez social media',
    subheadline: 'Posty, które pokazują efekty i budują pewność siebie klientek. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '💅 Wiosenna metamorfoza paznokci! Ostatnie wolne terminy w tym tygodniu. Zarezerwuj przez DM lub link poniżej 👇' },
      { platform: 'instagram', content: 'Przed i po 🌟 Każdy zabieg to nowa wersja siebie. Zarezerwuj termin! #salon #paznokcie #glow' },
      { platform: 'tiktok', content: '5 minut dla siebie — dlaczego każda kobieta potrzebuje wizyty u nas 💆‍♀️ #salon #beauty #paznokcie' },
    ],
    socialProof: { name: 'Natalia P.', business: 'Salon kosmetyczny w Warszawie', quote: 'Klientki mówią, że znalazły mnie przez Instagram. Grafik zajęty na 3 tygodnie do przodu.' },
    metaTitle: 'PostujTo dla salonów kosmetycznych — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla salonu kosmetycznego. Więcej rezerwacji dzięki FB i IG.',
  },
  {
    slug: 'fryzjer', name: 'Fryzjer / Barber', icon: '✂️',
    headline: 'Twój salon fryzjerski zawsze aktywny w social mediach',
    subheadline: 'Generuj posty na FB i IG w 30 sekund. Bez agencji, bez stresu.',
    examplePosts: [
      { platform: 'facebook', content: '✂️ Wiosenna metamorfoza już od [CENA] zł! Umów się dziś — mamy wolne terminy w tym tygodniu. Zadzwoń lub napisz na DM 👇' },
      { platform: 'instagram', content: 'Przed i po 🌟 Każda fryzura to nowa historia. Jaka będzie Twoja? #fryzjer #metamorfoza #salon' },
      { platform: 'tiktok', content: 'Jak w 3 krokach umówić wizytę bez telefonu? Sprawdź bio 👆 #fryzjer #porada #booking' },
    ],
    socialProof: { name: 'Magda K.', business: 'Studio Fryzjerskie w Krakowie', quote: 'Zaoszczędziłam 3 godziny tygodniowo. Posty wychodzą lepsze niż robiłam sama.' },
    metaTitle: 'PostujTo dla fryzjerów — autopilot social mediów | PostujTo',
    metaDescription: 'Generuj profesjonalne posty dla salonu fryzjerskiego w 30 sekund. Zacznij za darmo.',
  },
  {
    slug: 'fitness', name: 'Fitness / Siłownia', icon: '💪',
    headline: 'Twoja siłownia rośnie, gdy posty pracują za Ciebie',
    subheadline: 'Motywujące posty dla klubowiczów. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '💪 Nowy miesiąc — nowe wyzwanie! Dołącz do naszej grupy i zmieniaj się razem z nami. Pierwsze zajęcia gratis 🎯' },
      { platform: 'instagram', content: 'Każdy trening przybliża Cię do celu 🔥 Zarezerwuj miejsce na jutrzejsze zajęcia! #fitness #silownia #trening' },
      { platform: 'tiktok', content: 'Co jeść po treningu, by spalać tłuszcz? Podpowiadamy! 🥗 #fitness #dieta #trening' },
    ],
    socialProof: { name: 'Piotr L.', business: 'Siłownia w Wrocławiu', quote: 'Liczba zapisów wzrosła o 25% po miesiącu używania PostujTo. Polecam każdemu klub fitness.' },
    metaTitle: 'PostujTo dla siłowni i fitness — posty social media | PostujTo',
    metaDescription: 'Motywujące posty dla klubu fitness i siłowni. Więcej zapisów dzięki FB i IG.',
  },
  {
    slug: 'stomatolog', name: 'Stomatolog', icon: '🦷',
    headline: 'Twój gabinet stomatologiczny polecany przez social media',
    subheadline: 'Posty, które budują zaufanie i eliminują strach. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🦷 Nie odkładaj wizyty na później! Bezbolesne leczenie i miła atmosfera. Umów się dziś — dostępne terminy w tym tygodniu 📅' },
      { platform: 'instagram', content: 'Piękny uśmiech to inwestycja w siebie 😁 Sprawdź naszą ofertę wybielania. #stomatolog #uśmiech #zdrowie' },
      { platform: 'tiktok', content: '5 pytań, które warto zadać dentyście, a zwykle nie zadajemy 🦷 #stomatolog #zdrowie #porada' },
    ],
    socialProof: { name: 'Kamila W.', business: 'Gabinet stomatologiczny w Gdyni', quote: 'Pacjenci mówią, że zaufali nam przez social media. Przyjęcia pełne na 6 tygodni.' },
    metaTitle: 'PostujTo dla stomatologów — posty social media | PostujTo',
    metaDescription: 'Posty budujące zaufanie dla gabinetu stomatologicznego. Zacznij za darmo.',
  },
  {
    slug: 'weterynarz', name: 'Weterynarz / Petsitter', icon: '🐾',
    headline: 'Twój gabinet weterynaryjny polecany przez właścicieli zwierząt',
    subheadline: 'Posty pełne troski i ciepła. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🐾 Wiosna = czas na odrobaczanie i szczepienia! Zarezerwuj wizytę dla swojego pupila — dostępne terminy w tym tygodniu 🐕' },
      { platform: 'instagram', content: 'Każdy pupil zasługuje na zdrowie i szczęście 🐈 Zadbaj o swojego zwierzaka. Umów wizytę! #weterynarz #pies #kot' },
      { platform: 'tiktok', content: 'Na co zwrócić uwagę, gdy Twój pies jest niespokojny? Podpowiadamy 🐶 #weterynarz #pies #porada' },
    ],
    socialProof: { name: 'Joanna S.', business: 'Lecznica weterynaryjna w Katowicach', quote: 'Nowi klienci mówią, że znaleźli nas na Instagramie. PostujTo oszczędza mi mnóstwo czasu.' },
    metaTitle: 'PostujTo dla weterynarzy — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla gabinetu weterynaryjnego. Więcej klientów z FB i IG.',
  },
  {
    slug: 'handel', name: 'Handel / Sklep', icon: '🏪',
    headline: 'Twój sklep — nowe kolekcje widzi więcej klientów online',
    subheadline: 'Posty, które sprzedają styl. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🛍️ Nowa dostawa właśnie weszła! Limitowane ilości — nie czekaj. Wpadnij do nas lub zamów przez stronę 👇' },
      { platform: 'instagram', content: 'Stylizacja tygodnia 🌟 Co nosisz w ten weekend? Znajdź swój look u nas. #moda #sklep #styl' },
      { platform: 'tiktok', content: 'Najlepszy bestseller tego miesiąca i dlaczego wszyscy go kupują 🔥 #sklep #moda #haul' },
    ],
    socialProof: { name: 'Beata R.', business: 'Sklep odzieżowy w Poznaniu', quote: 'Klientki przychodzą i mówią, że widziały post na Instagramie. Sprzedaż online wzrosła.' },
    metaTitle: 'PostujTo dla sklepów i handlu — posty social media | PostujTo',
    metaDescription: 'Posty sprzedażowe dla sklepu i handlu na FB i IG. Więcej klientów w 30 sekund.',
  },
  {
    slug: 'rekodzielnictwo', name: 'Rękodzielnictwo', icon: '🧶',
    headline: 'Twoje rękodzieło widzi cały internet — bez wysiłku',
    subheadline: 'Posty, które pokazują duszę produktu i unikalność rzemiosła. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🧶 Każdy produkt to unikalna historia. Ręcznie zrobiony [PRODUKT] już dostępny! Zamów personalizację przez DM 💌' },
      { platform: 'instagram', content: 'Z warsztatu na Twoje półki 🌿 Każdy detal robiony z miłością. #rękodzieło #handmade #prezent' },
      { platform: 'tiktok', content: 'Jak powstaje [PRODUKT] od pierwszej nitki? Pokaż nam proces ✨ #handmade #rekodzielnictwo #diy' },
    ],
    socialProof: { name: 'Ela K.', business: 'Pracownia rękodzieła w Krakowie', quote: 'Instagram stał się moim głównym kanałem sprzedaży. PostujTo pomaga mi publikować regularnie.' },
    metaTitle: 'PostujTo dla rękodzielników — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla pracowni rękodzieła. Pokaż wyjątkowość na FB i IG.',
  },
  {
    slug: 'budowlanka', name: 'Budowlanka / Remont', icon: '🏗️',
    headline: 'Twoja firma budowlana — zlecenia przez social media',
    subheadline: 'Posty, które budują zaufanie przez dowody i realizacje. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🏗️ Właśnie zakończyliśmy kolejną realizację! Od surowych ścian do wymarzonego salonu. Pytaj o wolne terminy 📲' },
      { platform: 'instagram', content: 'Przed i po remoncie 🔨 Nasza ekipa dba o każdy detal. #remont #budowlanka #realizacja' },
      { platform: 'tiktok', content: '3 rzeczy, o których zapominasz przy planowaniu remontu 🏠 #budowlanka #remont #porada' },
    ],
    socialProof: { name: 'Krzysztof J.', business: 'Firma remontowa w Warszawie', quote: 'Klienci dzwonią i mówią, że znaleźli nas na Facebooku. Zapełniłem kalendarz na 3 miesiące.' },
    metaTitle: 'PostujTo dla firm budowlanych — posty social media | PostujTo',
    metaDescription: 'Posty budujące zaufanie dla firm remontowych i budowlanych. Zacznij za darmo.',
  },
  {
    slug: 'uslugi', name: 'Usługi / Rzemiosło', icon: '🔧',
    headline: 'Twoja firma usługowa — klienci przez social media',
    subheadline: 'Posty, które pokazują profesjonalizm i budują zaufanie. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🔧 Szybka, rzetelna realizacja! Skontaktuj się z nami — bezpłatna wycena w 24h. Dostępne terminy w tym tygodniu 📅' },
      { platform: 'instagram', content: 'Realizacja tygodnia ✅ Przyszedł problem — wyszło rozwiązanie. #usługi #rzemiosło #fachowiec' },
      { platform: 'tiktok', content: 'Jak wybrać rzetelnego fachowca? 5 pytań, które musisz zadać 🔧 #usługi #porada #fachowiec' },
    ],
    socialProof: { name: 'Artur M.', business: 'Firma usługowa w Łodzi', quote: 'Przez social media pozyskuję 2-3 nowych klientów miesięcznie. PostujTo robi to za mnie.' },
    metaTitle: 'PostujTo dla firm usługowych — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla firm usługowych i rzemieślniczych. Więcej zleceń.',
  },
  {
    slug: 'fotograf', name: 'Fotograf', icon: '📸',
    headline: 'Twoje zdjęcia widzi cały internet — czas na social media',
    subheadline: 'Posty, które oddają emocje i przyciągają nowych klientów. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '📸 Ostatnie wolne terminy na sesje komunijne! Piękne wspomnienia, które zostają na zawsze. Zarezerwuj termin 👇' },
      { platform: 'instagram', content: 'Każde ujęcie opowiada historię 🌟 Zaufaj nam swoje wyjątkowe chwile. #fotograf #sesja #wspomnienia' },
      { platform: 'tiktok', content: 'Jak przygotować się do sesji biznesowej? 5 szybkich rad 📸 #fotograf #sesja #porada' },
    ],
    socialProof: { name: 'Michał T.', business: 'Studio fotograficzne w Wrocławiu', quote: 'Instagram generuje połowę moich zapytań. PostujTo sprawia, że zawsze jestem aktywny.' },
    metaTitle: 'PostujTo dla fotografów — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla fotografa na FB i IG. Więcej klientów dzięki social mediom.',
  },
  {
    slug: 'ogrodnik', name: 'Ogrodnik / Landscaping', icon: '🌿',
    headline: 'Twoje usługi ogrodnicze — rozchwytywane dzięki social mediom',
    subheadline: 'Posty sezonowe, które pokazują efekty pracy. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🌿 Wiosenny przegląd ogrodów — zarezerwuj swoją ekipę przed sezonem! Wolne terminy tylko do końca marca 📅' },
      { platform: 'instagram', content: 'Przed i po — jak w 3 godziny zmieniliśmy ten ogród 🌸 #ogrodnik #ogród #landscaping' },
      { platform: 'tiktok', content: 'Top 5 roślin, które wyglądają pięknie i nie wymagają uwagi 🌱 #ogrodnik #ogród #rośliny' },
    ],
    socialProof: { name: 'Paweł G.', business: 'Firma ogrodnicza w Poznaniu', quote: 'Sezon jeszcze nie zaczął, a już mam pełen grafik. Social media naprawdę działają.' },
    metaTitle: 'PostujTo dla ogrodników — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla firm ogrodniczych i landscaping. Więcej zleceń sezonowych.',
  },
  {
    slug: 'transport', name: 'Transport / Spedycja', icon: '🚛',
    headline: 'Twoja firma transportowa — zaufana przez social media',
    subheadline: 'Posty, które budują pewność i pokazują niezawodność. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🚛 Kolejny ładunek bezpiecznie u klienta! Niezawodny transport PL-DE-FR — zapytaj o wycenę 📲' },
      { platform: 'instagram', content: 'Terminowość i bezpieczeństwo — nasze priorytety ✅ Poznaj naszą flotę. #transport #spedycja #logistyka' },
      { platform: 'tiktok', content: 'Jak pakujemy kruche towary, by dojeżdżały bez uszkodzeń? 📦 #transport #logistyka #porada' },
    ],
    socialProof: { name: 'Dariusz K.', business: 'Firma transportowa w Katowicach', quote: 'Klienci mówią, że wyglądamy profesjonalnie w sieci. PostujTo pomaga mi budować markę.' },
    metaTitle: 'PostujTo dla firm transportowych — posty social media | PostujTo',
    metaDescription: 'Posty budujące zaufanie dla firm transportowych i spedycyjnych. Zacznij za darmo.',
  },
  {
    slug: 'prawnik', name: 'Kancelaria / Prawnik', icon: '⚖️',
    headline: 'Twoja kancelaria — klienci przez profesjonalne social media',
    subheadline: 'Posty eksperckie, które budują autorytet i zaufanie. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '⚖️ Nie podpisuj umowy bez konsultacji! 3 błędy, które mogą Cię drogo kosztować. Bezpłatna konsultacja — napisz do nas 👇' },
      { platform: 'instagram', content: 'Prawo nie musi być skomplikowane 📋 Pomagamy w sposób zrozumiały. #prawnik #kancelaria #prawo' },
      { platform: 'tiktok', content: '3 błędy przy podpisywaniu umowy najmu — musisz to wiedzieć ⚖️ #prawnik #prawo #porada' },
    ],
    socialProof: { name: 'Marta Z.', business: 'Kancelaria prawna w Warszawie', quote: 'Klienci mówią, że posty brzmią autorytatywnie. PostujTo pomaga mi dotrzeć do nowych osób.' },
    metaTitle: 'PostujTo dla prawników — posty social media | PostujTo',
    metaDescription: 'Profesjonalne posty dla kancelarii prawnej na FB i LI. Więcej klientów online.',
  },
  {
    slug: 'korepetycje', name: 'Korepetycje', icon: '📚',
    headline: 'Twoje korepetycje — pełen grafik dzięki social mediom',
    subheadline: 'Posty, które trafiają do rodziców i uczniów. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '📚 Ostatnie miejsca przed maturą! Indywidualne korepetycje z matematyki i angielskiego. Pytaj przez DM 👇' },
      { platform: 'instagram', content: 'Matematyka nie musi być trudna 🎯 Nasze wyniki mówią same za siebie. #korepetycje #nauka #matura' },
      { platform: 'tiktok', content: 'Jak skutecznie uczyć się matematyki? 3 triki, które działają 📐 #korepetycje #nauka #matura' },
    ],
    socialProof: { name: 'Monika L.', business: 'Korepetycje online z Trójmiasta', quote: 'Grafik pełny na 2 miesiące do przodu. Rodzice piszą, że znaleźli mnie przez Facebooka.' },
    metaTitle: 'PostujTo dla korepetytorów — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla korepetytora na FB i IG. Więcej uczniów przez social media.',
  },
  {
    slug: 'edukacja', name: 'Edukacja / Kursy', icon: '🎓',
    headline: 'Twoje kursy sprzedają się przez social media — automatycznie',
    subheadline: 'Posty, które pokazują wartość i ROI. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🎓 Nowa edycja kursu startuje w przyszłym miesiącu! Ostatnie miejsca — zapisz się i zmień swoje życie zawodowe 👇' },
      { platform: 'instagram', content: 'Inwestycja w siebie, która się zwraca 💡 Sprawdź, co osiągnęli nasi absolwenci. #edukacja #kursy #rozwój' },
      { platform: 'tiktok', content: 'Nauczyłem się [UMIEJĘTNOŚĆ] w 30 dni i teraz zarabiam o 20% więcej 🚀 #edukacja #kursy #kariera' },
    ],
    socialProof: { name: 'Rafał N.', business: 'Platforma kursów online', quote: 'Liczba zapisów wzrosła o 40% po regularnym postowaniu. PostujTo to najlepsza inwestycja.' },
    metaTitle: 'PostujTo dla platform edukacyjnych — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla kursów online i edukacji. Więcej zapisów przez FB i IG.',
  },
  {
    slug: 'nieruchomosci', name: 'Nieruchomości', icon: '🏠',
    headline: 'Twoje oferty nieruchomości docierają do więcej kupujących',
    subheadline: 'Posty, które sprzedają marzenie o własnym kącie. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '🏠 Nowa oferta! Mieszkanie z tarasem, [METRAŻ] m², [DZIELNICA]. Zapraszam na prezentację — wolne terminy w tym tygodniu 📅' },
      { platform: 'instagram', content: 'Twoje wymarzone miejsce czeka 🌟 Oferta tygodnia — sprawdź szczegóły w linku w bio. #nieruchomości #mieszkanie #dom' },
      { platform: 'tiktok', content: 'Jak kupić pierwsze mieszkanie i nie oszaleć od formalności? 🏠 #nieruchomości #mieszkanie #porada' },
    ],
    socialProof: { name: 'Agnieszka W.', business: 'Biuro nieruchomości w Warszawie', quote: 'Klienci mówią, że oferta wygląda profesjonalnie. PostujTo pomaga mi wyróżnić się na rynku.' },
    metaTitle: 'PostujTo dla agentów nieruchomości — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla biura nieruchomości. Więcej zapytań przez FB i IG.',
  },
  {
    slug: 'turystyka', name: 'Turystyka / Hotel', icon: '✈️',
    headline: 'Twój hotel czy biuro podróży — pełne rezerwacje przez social media',
    subheadline: 'Posty, które budzą marzenia o wakacjach. Gotowe w 30 sekund.',
    examplePosts: [
      { platform: 'facebook', content: '✈️ Last minute! Wolny pokój na ten weekend w specjalnej cenie. Zarezerwuj teraz, zanim ktoś Cię uprzedzi 👇' },
      { platform: 'instagram', content: 'Śniadanie z widokiem na góry 🏔️ Tak może wyglądać Twój poranek. Zarezerwuj pobyt! #hotel #wakacje #turystyka' },
      { platform: 'tiktok', content: '3 ukryte miejsca w okolicy, których nie znajdziesz w przewodnikach 🗺️ #turystyka #podróże #travel' },
    ],
    socialProof: { name: 'Wojciech H.', business: 'Hotel górski w Zakopanem', quote: 'Rezerwacje przez social media wzrosły o 35%. PostujTo pomaga nam być widocznymi przez cały rok.' },
    metaTitle: 'PostujTo dla hoteli i turystyki — posty social media | PostujTo',
    metaDescription: 'Automatyczne posty dla hotelu i biura podróży. Więcej rezerwacji przez FB i IG.',
  },
];

// 105 tematów (5 per branża) — używane na Landing Pages i w tabeli Supabase industry_inspirations
// Typ: 'pain' = Ból klienta, 'result' = Rezultat, 'relation' = Kulisy/Relacja
export const INDUSTRY_TOPICS: Record<string, { title: string; type: 'pain' | 'result' | 'relation' }[]> = {
  restauracja: [
    { title: 'Dlaczego nasza [Danie Dnia] smakuje inaczej niż wszędzie?', type: 'relation' },
    { title: '3 powody, by dziś nie gotować obiadu w domu.', type: 'pain' },
    { title: 'Zajrzyj do naszej kuchni: Jak powstaje Twój ulubiony sos?', type: 'relation' },
    { title: 'Romantyczna kolacja czy szybki lunch? Mamy stolik dla Ciebie.', type: 'result' },
    { title: 'Co nasi goście mówią o [Danie]? Zobacz opinie!', type: 'result' },
  ],
  catering: [
    { title: 'Ile czasu marnujesz na zakupy i gotowanie w tygodniu?', type: 'pain' },
    { title: 'Jak schudnąć 3 kg w miesiąc bez głodówki? Nasz plan.', type: 'result' },
    { title: 'Co znajdziesz w jutrzejszej torbie? Menu na jutro!', type: 'relation' },
    { title: '3 mity o cateringu dietetycznym, które musisz znać.', type: 'pain' },
    { title: 'Z czego gotujemy? Poznaj naszych lokalnych dostawców.', type: 'relation' },
  ],
  piekarnia: [
    { title: 'Dlaczego nasz chleb na zakwasie nie czerstwieje po jednym dniu?', type: 'pain' },
    { title: 'Zapach, który budzi całą ulicę — co właśnie wyjęliśmy z pieca!', type: 'result' },
    { title: 'Chleb z marketu vs rzemieślniczy: zobacz różnicę w składzie.', type: 'pain' },
    { title: 'Twoje idealne śniadanie zaczyna się tutaj. Co wybierasz?', type: 'result' },
    { title: 'Nasz piekarz pracuje, gdy Ty śpisz — kulisy nocy w piekarni.', type: 'relation' },
  ],
  sklep: [
    { title: 'Nowa dostawa świeżych warzyw! Zobacz, co dziś przyjechało.', type: 'result' },
    { title: '3 produkty z naszego sklepu, które musisz mieć w kuchni.', type: 'result' },
    { title: 'Lokalne produkty, których nie znajdziesz w wielkich marketach.', type: 'pain' },
    { title: 'Szybki przepis na kolację z produktów z naszej półki.', type: 'result' },
    { title: 'Jesteśmy tu dla Was — poznaj naszą ekipę sprzedawców!', type: 'relation' },
  ],
  kosmetyczka: [
    { title: 'Twoja skóra po zimie potrzebuje ratunku. Zobacz nasz plan.', type: 'pain' },
    { title: 'Metamorfoza paznokci: Od zniszczonych do perfekcyjnych.', type: 'result' },
    { title: '5 minut dla siebie — dlaczego każda kobieta potrzebuje wizyty u nas?', type: 'result' },
    { title: 'Czym pracujemy? Zobacz nasze profesjonalne kosmetyki.', type: 'relation' },
    { title: 'Najczęściej zadawane pytania o zabieg [Nazwa]. Odpowiadamy!', type: 'pain' },
  ],
  fryzjer: [
    { title: 'Twoje włosy się puszą? Przestań robić te 3 błędy pod prysznicem.', type: 'pain' },
    { title: 'Metamorfoza miesiąca: od spalonego blondu do lśniącego brązu.', type: 'result' },
    { title: 'Nasze nowe narzędzia — dlaczego inwestujemy w najlepszy sprzęt?', type: 'relation' },
    { title: 'Barberski klasyk czy nowoczesny fade? Co wybierasz?', type: 'relation' },
    { title: 'Szybkie odświeżenie wyglądu przed weekendem — mamy wolne terminy!', type: 'result' },
  ],
  fitness: [
    { title: 'Boisz się pierwszej wizyty na siłowni? Nie u nas! Zobacz dlaczego.', type: 'pain' },
    { title: 'Trening personalny vs samodzielny: Co daje szybsze efekty?', type: 'pain' },
    { title: 'Twoja godzina mocy — energia z naszych zajęć grupowych!', type: 'result' },
    { title: 'Co jeść po treningu, by spalać tłuszcz? Podpowiadamy.', type: 'result' },
    { title: 'Nasi klubowicze zmieniają życie — poznaj historię [Imię].', type: 'relation' },
  ],
  stomatolog: [
    { title: 'Boisz się dentysty? U nas każda wizyta jest bezbolesna.', type: 'pain' },
    { title: 'Wybielanie zębów: Efekty już po pierwszej wizycie. Przed i po.', type: 'result' },
    { title: '5 pytań, które warto zadać dentyście, a zwykle nie zadajemy.', type: 'pain' },
    { title: 'Jak dbać o zęby między wizytami? 3 rady od naszego ortodonty.', type: 'result' },
    { title: 'Poznaj nasz gabinet — komfort, który poczujesz już w poczekalni.', type: 'relation' },
  ],
  weterynarz: [
    { title: 'Twój pupil nie powie Ci, że go boli. Na co zwrócić uwagę?', type: 'pain' },
    { title: 'Pierwsza wizyta u weterynarza — jak oszczędzić stresu zwierzakowi?', type: 'result' },
    { title: 'Szczęśliwy pies to zdrowy pies. Zadbaj o profilaktykę.', type: 'result' },
    { title: 'Wyjeżdżasz? Zostaw pupila w dobrych rękach — jak u nas mieszkają.', type: 'relation' },
    { title: 'Nasi pacjenci to nasza pasja — zobacz dzisiejszych gości!', type: 'relation' },
  ],
  handel: [
    { title: 'Nie wiesz, co założyć na [Okazja]? Mamy 3 gotowe stylizacje.', type: 'pain' },
    { title: 'Nowa kolekcja już w sklepie! Zobacz nasze ulubione modele.', type: 'result' },
    { title: 'Jakość, którą poczujesz — zobacz zbliżenie na materiał.', type: 'result' },
    { title: 'Wasze zdjęcia w naszych ubraniach — dziękujemy za zaufanie!', type: 'relation' },
    { title: 'Bestseller tygodnia: Dlaczego wszyscy kupują [Produkt]?', type: 'result' },
  ],
  rekodzielnictwo: [
    { title: 'Dlaczego rękodzieło to idealny prezent? Unikalność ma znaczenie.', type: 'result' },
    { title: 'Z warsztatu: Zobacz, jak powstaje [Produkt] od pierwszej nitki.', type: 'relation' },
    { title: 'Personalizacja: Napiszemy na produkcie, co tylko zechcesz!', type: 'result' },
    { title: 'Detale, które robią różnicę — zbliżenie na wykonanie.', type: 'result' },
    { title: 'Pakowanie prezentowe w cenie! Zobacz, jak pięknie wysyłamy paczki.', type: 'relation' },
  ],
  budowlanka: [
    { title: 'Zły remont to koszmar. Zobacz, jak pracujemy z dbałością o detale.', type: 'pain' },
    { title: 'Od surowych ścian do wymarzonego salonu — nasza ostatnia realizacja.', type: 'result' },
    { title: '3 rzeczy, o których zapominasz przy planowaniu instalacji elektrycznej.', type: 'pain' },
    { title: 'Czystość na budowie? Tak, u nas to standard.', type: 'relation' },
    { title: 'Terminy na sezon — zarezerwuj swoją ekipę już teraz!', type: 'result' },
  ],
  uslugi: [
    { title: 'Jak wybrać rzetelnego fachowca? 5 pytań, które musisz zadać.', type: 'pain' },
    { title: 'Nasza realizacja tygodnia — z problemem do rozwiązania w jeden dzień.', type: 'result' },
    { title: 'Transparentna wycena: Skąd pochodzi cena naszej usługi?', type: 'relation' },
    { title: 'Gwarancja na każdą usługę — co to oznacza w praktyce?', type: 'result' },
    { title: 'Poznaj nasz zespół — ludzie, którym możesz zaufać swoje sprawy.', type: 'relation' },
  ],
  fotograf: [
    { title: 'Nie lubisz być na zdjęciach? Sprawię, że poczujesz się swobodnie.', type: 'pain' },
    { title: 'Sesja rodzinna: Idealna pamiątka, która nie wyblaknie.', type: 'result' },
    { title: 'Jak przygotować się do sesji biznesowej? 5 szybkich rad.', type: 'result' },
    { title: 'Zza kulis: Jak wygląda sesja w plenerze od strony fotografa.', type: 'relation' },
    { title: 'Ostatnie wolne terminy na sesje komunijne/ślubne!', type: 'result' },
  ],
  ogrodnik: [
    { title: 'Wiosna w ogrodzie — co zrobić w pierwszej kolejności?', type: 'pain' },
    { title: 'Przed i po: Jak w 3 godziny zmieniliśmy ten ogród nie do poznania.', type: 'result' },
    { title: 'Top 5 roślin, które wyglądają pięknie i nie wymagają uwagi.', type: 'result' },
    { title: 'Jeden dzień z naszą ekipą — jak wygląda kompleksowa pielęgnacja?', type: 'relation' },
    { title: 'Zamów przegląd ogródka przed sezonem — wolne terminy!', type: 'result' },
  ],
  transport: [
    { title: 'Co się dzieje z Twoim towarem na granicy? Jak uniknąć przestojów.', type: 'pain' },
    { title: 'Trasa PL-DE w 24h. Kolejny ładunek bezpiecznie u klienta.', type: 'result' },
    { title: 'Poznajcie Darka — naszego mistrza kierownicy z 10-letnim stażem.', type: 'relation' },
    { title: 'Jak pakujemy kruche towary, by dojeżdżały w 100% nieuszkodzone?', type: 'result' },
    { title: 'Nasz GPS śledzi każdą przesyłkę w czasie rzeczywistym.', type: 'relation' },
  ],
  prawnik: [
    { title: '3 błędy przy podpisywaniu umowy najmu, które mogą Cię drogo kosztować.', type: 'pain' },
    { title: 'Jak skutecznie dochodzić swoich praw bez znajomości prawa?', type: 'pain' },
    { title: 'Wygraliśmy sprawę o odszkodowanie dla poszkodowanego w wypadku.', type: 'result' },
    { title: 'Bezpłatna konsultacja: Co Ci przysługuje przed podjęciem decyzji o pozwie?', type: 'result' },
    { title: 'Poznaj nasz zespół — prawnicy, którym możesz zaufać swoje sprawy.', type: 'relation' },
  ],
  korepetycje: [
    { title: 'Matematyka nie musi być trudna. Pokażemy Ci sposób na [Temat].', type: 'result' },
    { title: 'Twoje dziecko stresuje się szkołą? Pomóż mu odzyskać pewność siebie.', type: 'pain' },
    { title: 'Wyniki naszych uczniów: Średnia ocen skoczyła o 1.5 stopnia!', type: 'result' },
    { title: 'Zajęcia online vs stacjonarne — co wybrać dla Twojego dziecka?', type: 'pain' },
    { title: 'Ostatnie miejsca w grupach przygotowujących do matury!', type: 'result' },
  ],
  edukacja: [
    { title: 'Naucz się [Umiejętność] w 30 dni i zacznij zarabiać więcej.', type: 'result' },
    { title: 'Dlaczego stare metody nauki nie działają? Poznaj nasz system.', type: 'pain' },
    { title: 'Zajrzyj do platformy: Jak wyglądają nasze lekcje wideo.', type: 'relation' },
    { title: 'Certyfikat, który otwiera drzwi — gdzie pracują nasi absolwenci?', type: 'result' },
    { title: 'Inwestycja w siebie to jedyna lokata, która się nie dewaluuje.', type: 'result' },
  ],
  nieruchomosci: [
    { title: 'Jak kupić pierwsze mieszkanie i nie oszaleć od formalności?', type: 'pain' },
    { title: 'Oferta tygodnia: Mieszkanie z tarasem, w którym się zakochasz.', type: 'result' },
    { title: 'Flip czy najem? W co teraz najlepiej zainwestować kapitał?', type: 'pain' },
    { title: 'Pustostany nie zarabiają. Zobacz, jak szybko znajdujemy najemców.', type: 'result' },
    { title: 'Dzień agenta: ile km zrobiliśmy, by znaleźć dom marzeń.', type: 'relation' },
  ],
  turystyka: [
    { title: 'Zapomnij o mailach i telefonach. Twój reset zaczyna się tutaj.', type: 'pain' },
    { title: 'Co zwiedzić w okolicy? 3 ukryte miejsca z dala od tłumów.', type: 'result' },
    { title: 'Śniadanie z widokiem na [Góry/Morze] — tak może wyglądać Twój poranek.', type: 'result' },
    { title: 'Poznaj ekipę, która zadba o Twój wypoczynek.', type: 'relation' },
    { title: 'Last minute: Wolny pokój na weekend w specjalnej cenie!', type: 'result' },
  ],
};
